const states = [
    { id: 1, label: 'Abia' },
    { id: 2, label: 'Adamawa' },
    { id: 3, label: 'Akwa Ibom' },
    { id: 4, label: 'Anambra' },
    { id: 5, label: 'Bauchi' },
    { id: 6, label: 'Bayelsa' },
    { id: 7, label: 'Benue' },
    { id: 8, label: 'Borno' },
    { id: 9, label: 'Cross river' },
    { id: 10, label: 'Delta' },
    { id: 11, label: 'Ebonyi' },
    { id: 12, label: 'Edo' },
    { id: 13, label: 'Ekiti' },
    { id: 14, label: 'Enugu' },
    { id: 15, label: 'Gombe' },
    { id: 16, label: 'Imo' },
    { id: 17, label: 'Jigawa' },
    { id: 18, label: 'Kaduna' },
    { id: 19, label: 'Kano' },
    { id: 20, label: 'Katsina' },
    { id: 21, label: 'Kebbi' },
    { id: 22, label: 'Kogi' },
    { id: 23, label: 'Kwara' },
    { id: 24, label: 'Lagos' },
    { id: 25, label: 'Nasarawa' },
    { id: 26, label: 'Niger' },
    { id: 27, label: 'Ogun' },
    { id: 28, label: 'Ondo' },
    { id: 29, label: 'Osun' },
    { id: 30, label: 'Oyo' },
    { id: 31, label: 'Plateau' },
    { id: 32, label: 'Rivers' },
    { id: 33, label: 'Sokoto' },
    { id: 34, label: 'Taraba' },
    { id: 35, label: 'Yobe' },
    { id: 36, label: 'Zamfara' },
    { id: 37, label: 'FCT' },
];

export const parties = [
    {id: 1, label:"A"},
    {id: 2, label:"AA"},
    {id: 3, label:"ADP"},
    {id: 4, label:"APP"},
    {id: 5, label:"AAC"},
    {id: 6, label:"ADC"},
    {id: 7, label:"APC"},
    {id: 8, label:"APGA"},
    {id: 9, label:"APM"},
    {id: 10, label:"BP"},
    {id: 11, label:"LP"},
    {id: 12, label:"NRM"},
    {id: 13, label:"NNPP"},
    {id: 14, label:"PDP"},
    {id: 15, label:"PRP"},
    {id: 16, label:"SDP"},
    {id: 17, label:"YPP"},
    {id: 18, label:"YP"},
    {id: 19, label:"ZLP"}
]
export default states;